### PR TITLE
Qmrlab standalone

### PR DESCRIPTION
**Pull request by tanguyduval**
I Finally found some time to push this branch
New function to create a standalone version of qMRLab using Matlab compiler runtime.
run use the function `qMRLab_make_standalone``
Add logos and splash screen that are in `qMRLab/docs/logos`
click on compile

Help is not available (cannot read help from compiled .m files)

I had to deal with models listing. a function qmrlab_static_models.m is created at compilation to list models. qMRLab was slightly modified to deal with that.

Find a compiled version for mac here https://osf.io/kcje6/download

### CODE REVIEW

**Comment by agahkarakuzu** [comment]
I have MCR installed, but version differences may be causing this. I will check. Can you also detail which MATLAB and OSX versions you are using? Oh, you 've just answered:D 

Making this a deployment step in a release pipeline would be amazing. At the time I have to give priority to other additions but it is at the back of my mind.

**Comment by tanguyduval** [comment]
If you compile qMRLab yourself, you will require the MCR version of your personal MATLAB
If you use my already compiled Matlab, that will download the right MCR
Please send me the error from the command:
`run_qMRLab.sh /Applications/MATLAB/MATLAB_Runtime/v94`

**Comment by agahkarakuzu** [comment]
I just tried the one from OSF and it did work 🎊 It is great that it automatically downloads the required MCR (R2018a), this way users don't have to deal with such details, cool! I've noticed that MCR in my local was already v94, but I attempted to compile it from R2015b. It should be OK when I compile from my R2018, as the process goes smoothly. 

image

I tried running `mt_sat` as an example. It downloaded the data, but ran into this issue:

image

**Comment by mathieuboudreau** [comment]
Looks like all the optional parameters have been made mandatory. This seems to suggest that compiling qMRLab might not preserve all the optional things we code, unless this is related to another change Tanguy made in the branch, unrelated to the compilation feature.


--
Mathieu Boudreau, PhD
Research Fellow, Montreal Heart Institute
Software Developer for qMRLab and AxonDeepSeg
438-822-8747 | www.github.com/mathieuboudreau

________________________________

**Comment by mathieuboudreau** [comment]
This relates to the question you raised at the lab meeting of "When do we release?" and "What constitutes which release version"?


My opinion would be to release on a predictable time table (e.g. first of every month/two months), and not create a compiled versions for minor (patch?) versions, only for "major" releases. We'd want the compiled versions to be the most stable of stable versions I think, sure compiling often has the benefit of adding all the bug fixes and new features, but it will also include all the new missed bugs, that not enough people have used/branched to discover yet.


Also, as a user, it might be a pain to be reminded to frequently download new compiled versions (it's not as easy as a git pull, right?). The user that will used the compiled version will likely download qMRLab once and never update it – if it's working correctly.


I agree, the compiled versions/releases should be tested much more extensively than our current versions – we likely should require more than 1 reviewer to test the GUI/Features before merging.


--
Mathieu Boudreau, PhD
Research Fellow, Montreal Heart Institute
Software Developer for qMRLab and AxonDeepSeg
438-822-8747 | www.github.com/mathieuboudreau

________________________________

**Comment by tanguyduval** [comment]
@mathieuboudreau the limitations of compiled version is that it cannot read or search .m files in the qMRLab folder. So
- help does not work --> cannot detect if optional or not
- Building the Model list is not possible
In my experience, the rest is running exactly the same way

Solution:
Generate a static help at compilation
Generate a static list of models at compilation. Done here:
https://github.com/neuropoly/qMRLab/blob/a5721a035e5a5cbf07dee9d78bd959c40ae16c93/src/Common/qMRLab_make_standalone.m#L1-L14

**Comment by tanguyduval** [comment]
I agree with Mathieu, we should compile on big releases. Just as I did for AxonSeg:
https://github.com/neuropoly/axonseg/releases/tag/v3.0

**Comment by agahkarakuzu** [comment]
> This relates to the question you raised at the lab meeting of "When do we release?" and "What constitutes which release version"?

Indeed, I also agree on compiling only for stable releases. Having GUI standalone is surely beautiful. @tanguyduval laid the groundwork to do this in Ubuntu as well, which can lead to another qMRLab docker image with GUI. 

 > help does not work --> cannot detect if optional or not

Is it possible to disable optional input validation feature with `isdeployed`, so that it won't be an issue on compiled version?

**Comment by tanguyduval** [comment]
Just added static help. that should solve the issue of optional argument for Octave (#275 ) and deployed app at the same time.
same link https://osf.io/kcje6/download
Best

**Comment by mathieuboudreau** [comment]
@tanguyduval I spoke with @agahkarakuzu, and he said that he'll take a look at this PR after the ISMRM deadline, as he's quite busy with that in the next two weeks. We could likely time this merge to go along with a new versioned release.

**Comment by mathieuboudreau** [comment]
@agahkarakuzu Think we're getting close to when we can release a standalone version?

**Comment by agahkarakuzu** [comment]
Let's decide what final additions we'd like to make for the next release: 

- [ ] [Add `mp2rage`](https://github.com/qMRLab/qMRLab/milestone/2)
- [ ]  [Have docker images ready in Dockerhub](https://github.com/qMRLab/qMRLab/milestone/4)
- [ ]  Others (please add) 

Then we can go ahead and compile for the next release. One important thing will be syncing Docker version tags with qMRLab versions. We had a discussion about this on Slack.

**Comment by mathieuboudreau** [comment]
Skip MP2RAGE for now, it is delayed, Nikola asked me to prfioritize the Jupyter Notebooks for the CONP meeting, so I don't know how soon when MP2RAGE will be finished.

**Comment by agahkarakuzu** [comment]
Alright @mathieuboudreau , do you have items in mind to expand that list?

**Comment by mathieuboudreau** [comment]
Not that I can think of @agahkarakuzu ; is there anything we mentioned in the ISMRM abstract that hasn't been merged to master yet?

**Comment by agahkarakuzu** [comment]
@mathieuboudreau stats module (but that one is not finishing anytime soon since I'll start a whole new thing here now). Plus we will need to create a container for the `mcr` (ubuntu).

**Comment by agahkarakuzu** [comment]
Using my admin privilages to merge this branch.  I will keep on working `deploy_tasks` branch to finalize.

**Pull request merged**
