### PR TITLE
Remove documentation from codebase

### PR DESCRIPTION
**Pull request by agahkarakuzu**
Lots of changes around moving documentation to `qmrlab/documentation` & improving docs. 

- During docgen, fits won't be performed anymore (faster)
- Much better layout 
- Method specific notes & citation convention 
- Identical codeblocks can be generated from comments  
- Will be automatically built & deployed by Azure release pipelines in sync with qmrlab/qmrlab.
- 

Temporary docs until we delete the old docs: 
https://qmrlabnew.readthedocs.io/

### CODE REVIEW

**Comment by agahkarakuzu** [comment]
Have to renew azure service connection, then CI tests will be triggered.

**Comment by agahkarakuzu** [comment]
- [ ] Add gendoc tests with different combinations of env vars w/o download and cat one of their output in the console

**Comment by agahkarakuzu** [comment]
@jvelazquez-reyes you'll see a `Deploy/Documentation/Notes/docGenericNotes.json`file in this branch. Can you please add one json struct per model each containing `model` (model name), `note` (you can leave it as an empty string for now) and `citation` sections? Then in the `citation` field, can you please add (ideally APA styled) citation to the reference article of the method (such as `yarnkyh et al...` for `b1_afi`) for the models with a reference in the header comment of their classdefs ?

You can later use this in the wrapper as well to populate the respective field.

**Comment by agahkarakuzu** [comment]
There is something fishy either about Octave 5.2.0 plots or the Docker env I temporarily created for @jvelazquez-reyes. @jvelazquez-reyes IIRC you have a local installation of Octave 5.2. If so, can you give plotModel of charmed a try?

**Comment by jvelazquez-reyes** [comment]
Yes @agahkarakuzu, I have an Octave 5.2 local installation. I have been trying with the function `Sim_Single_Voxel_Curve` where there's a call to `plotModel` but I didn't find anything suspicious, the output looks fine and no error showed up.

I also downloaded the OSF dataset to fit it using the `charmed` model. Although the FitResults folder is created, and the outputs appear to be fine, the progress bar freezes and apparently the process is never completed. I ran it several times and that's the only strange behaviour I noticed.

imagen

**Comment by agahkarakuzu** [comment]
Cool, now can you run the following (after checking out this branch) by starting octave using `octave-cli`, then 

```octave
moxunit_runtests('Test/MoxUnitCompatible/quickMoxTests/plotmodel_test.m');
```

and see if it completes?

**Comment by jvelazquez-reyes** [comment]
It completes.

imagen

**Comment by agahkarakuzu** [comment]
Thanks @jvelazquez-reyes, can you confirm (list) the models tested from the log?

**Comment by jvelazquez-reyes** [comment]
The models tested were amico, charmed, dti, noddi, qmt_bssfp, qmt_sirfse, qmt_spgr, inversion_recovery, mono_t2, mwf.

**Comment by agahkarakuzu** [comment]
Thanks! This confirms that there is something off with the environment. I'll look into this!

**Comment by agahkarakuzu** [comment]
Looks like font update did the trick: 

image

I am pushing this to dockerhub, will confirm by switching action base image to the new image I built.

**Comment by agahkarakuzu** [comment]
Great, this worked! Means that we can now have a build matrix to test for multiple Octave versions, which was not possible before so easily. 

@jvelazquez-reyes can you flag any leftover `if octave do not plot` conditions I placed in the files changed?

**Pull request merged**
