### PR TITLE
MTV

### PR DESCRIPTION
**Pull request by tanguyduval**
## Purpose
Make a proper MTV module: Mezer et al. Nat Med. 2013

## Approach
- Use outputs of vf1_t1 as inputs + Brain Mask
- Simplified version of mrQ package (https://github.com/mezera/mrQ) : no multicoil dataset needed. Use a spline function instead for reception profile
- No example dataset yet

#### Open Questions and Pre-Merge TODOs
- [ ] Use github checklists. When solved, check the box and explain the answer.

- [ ] Review that changed source files/lines are related to the pull request/issue
_If any files/commits were accidentally included, cherry-pick them into another branch._

- [ ] Review that changed source files/lines were not accidentally deleted
_Fix appropriately if so._

- [ ] Test new features or bug fix
_If not implemented/resolved adequately, solve it or inform the developer by requesting changes in your review._
_Preferably, set breakpoints in the locations that the code was changed and follow allong line by line to see if the code behaves as intended._

##### Manual GUI tests (general)

- [ ] Does the qMRLab GUI open?
- [ ] Can you change models?
- [ ] Can you load a data folder for a model?
- [ ] Can you view data?
- [ ] Can you zoom in the image?
- [ ] Can you pan out of the image?
- [ ] Can you view the histogram of the data?
- [ ] Can you change the color map?
- [ ] Can you fit dataset (Fit data)?
- [ ] Can you save/load the results?
- [ ] Can you open the options panel?
- [ ] Can you change option parameters?
- [ ] Can you save/load option paramters?
- [ ] Can you select a voxel?
- [ ] Can you fit the data of that voxel ("View data fit")?
- [ ] Can you simulate and fit a voxel ("Single Voxel Curve")?
- [ ] Can you run a Sensitivity Analysis?
- [ ] Can you simulate a Multi Voxel Distribution?

##### Specifications

  - Version: 2.4.1
  - Platform: mac
  - Subsystem: matlab R2019

### CODE REVIEW

**Comment by tanguyduval** [comment]
Ok, I think the module is ready. I get the same exact results as Frank F. Yu.
And values in the white matter are consistent with Mezer et al. 2013:
  * Our measurements:
image
  * Mezer et al.:
image
  
Also, just added the dataset shared by Frank F. Yu as an example. @jcohenadad how shall we cite this dataset?

@agahkarakuzu if you could try to run the batch and the GUI on your side, that would be perfect 👍 

Best
Tanguy

**Comment by tanguyduval** [comment]
Qualitative comparison between paper fig 1 (left) and the example dataset (right):
image

Not the exact same implementation as my paper on scan-rescan MRM 2017. Indeed we cannot use the same implementation for spinal cord and Brain for mtv... 
I don't remember on which dataset this implementation for the brain was tuned and used. Would need a more thorough validation.

**Comment by agahkarakuzu** [comment]
Thank you so much @tanguyduval I gave it a go, looks beautiful! 

I received a warning from 

```
if length(find(CSF2))<200
           fprintf(['\n Warning: We could find only ' num2str(length(find(CSF2))) ' csf voxels. This makes the CSF WF estimation very noisy. Consider adapting CSF.nii and normalizing on your own              \n']);
end
```

Should we be more specific about how to do this?

**Comment by tanguyduval** [comment]
@agahkarakuzu good point!
I added an option to reduce the T1 threshold for the CSF mask
Best

**Comment by agahkarakuzu** [comment]
Thank you @tanguyduval ! All good on my end.

**Review by agahkarakuzu — APPROVED** [review]

**Comment by agahkarakuzu** [comment]
The travis test fails again w/o complete log. Which motivates me more toward #412.

**Comment by agahkarakuzu** [comment]
Matlab tests passed. Thank you so much @tanguyduval!

**Pull request merged**
