### PR TITLE
JOSS Review #2 

### PR DESCRIPTION
**Pull request by agahkarakuzu**
This PR addresses [comments](https://github.com/openjournals/joss-reviews/issues/2343#issuecomment-665174542) by @mfroeling and @Kevin-Mattheus-Moerman. 

The revised version can be tested at the [`joss_rev2`](https://github.com/qMRLab/qMRLab/tree/joss_rev2) branch. 

*** 

|Comments by @Kevin-Mattheus-Moerman | Response|
|-----|----|
| Missing DOIs. | https://github.com/qMRLab/qMRLab/commit/ebf5b11b10fdacbd57de95930e930aa0a819ae2b |

@Kevin-Mattheus-Moerman I will ask whedon to perform a DOI check after this PR is reviewed and merged. 

*** 

|Comments by @mfroeling | Response|
|-----|----|
| When the toolbox starts it needs a check if the needed Matlab dependencies are installed. The first few tries I had issues during data processing that were due to missing or badly installed packages. Especially for the missing packages, there should be a strong warning when starting the toolbox that it will not run properly.| The [GUI documentation](https://qmrlab.readthedocs.io/en/master/gui-example.html) suggests that users run `startup.m` before starting the GUI. Normally, `startup.m` checks whether the `Image Processing` and `Optimization` toolboxes are installed. However, I agree that is a fundamental requirement and should be controlled for even when the `startup` is not run in advance. Resolved by https://github.com/qMRLab/qMRLab/commit/c03f67fc91f30b3cfcc0b56186adf243b951593b. |
|Example data is provided for the T1 relaxometry in the documentation. After some browsing the GUI I found the download example button also for other modalities. This should be better documented. I started with the command line and there I could not find a list of available example data. | qMRLab provides an example dataset per model. I created a [new section](https://qmrlab.readthedocs.io/en/joss_rev2/example_datasets.html#) in the documentation about example datasets for clarity  https://github.com/qMRLab/qMRLab/commit/3c1bd2b7982a50bfb49423e9dec0630c5e9f518e.|
| Each model needs a specific data setup that is apparently inferred from the files in the folder. One can load each data needed separately or by selecting the containing folder. However, for me, it is not clear how the data structure/naming should be for every type of data supported if one wants to used the predefined data format. For example, when additional data quantitative data is loaded how should this be stored (e.g. B1 can be fraction or percent).| The convention for specific data setups (i.e. data names) are only followed for example datasets to make systematic script generation easier for CI tests and to automatically load inputs after `Download Example` link in the GUI is clicked. The [new documentation](https://qmrlab.readthedocs.io/en/joss_rev2/gui-example.html#download-example-data) makes a note about it. <br><br> Information regarding the data structure is fetched from the [header comments](https://github.com/qMRLab/qMRLab/blob/6c14248218dc854e431ee665c55dc0a698a3d44a/src/Models/T1_relaxometry/vfa_t1.m#L6-L11) of the class definitions. Previously, users had to hover the cursor over the input labels, or click the `?` button to access this information. Commit https://github.com/qMRLab/qMRLab/commit/6c14248218dc854e431ee665c55dc0a698a3d44a now exposes this information to the input (text) box for user's convenience. Classdef headers were revisited to make input data descriptions more informative. For example, now it is obvious that `B1+` maps are expected to be normalized. | 
| I loaded one of my own diffusion sets and the bval/bvec files were not loaded or asked for. without this information the tool still allowed me to click the fit button resulting in errors. Only after some exploration I found the load bval/bvec in the options pannel. Nowhere in the help of the diffusion does it state that I have to load my own bval/bvec files.| The default `Protocol` parameters are intended for the example datasets. A [warning](https://qmrlab.readthedocs.io/en/joss_rev2/example_datasets.html) is added to the new documentation, advising users against using default parameters to fit their own data. <br><br> I agree that the protocol tables of the diffusion models are more crowded compared to the other models, which makes them less favorable to populate using `Add` `Remove` buttons located at the bottom of the `Options` panel. Despite that alternative ways existed, I noticed that they were not well documented. Thank you so much for bringing this to my attention! Commit https://github.com/qMRLab/qMRLab/commit/3c1bd2b7982a50bfb49423e9dec0630c5e9f518e adds a help button to the protocol panel for the models with `tabletip` property and gives a way to open a web page that contains information about how to populate respective protocols. This feature is made available for all the diffusion models, please see the **Screenshot-1** below.   |
|different models ask for different input files. This is nicely provided in the GUI however I would be nice if mandatory and optional inputs would be clear. For example, with DTI processing I don't need a mask or SigmaNoise to be able to fit a Tensor.| Commit https://github.com/qMRLab/qMRLab/commit/6c14248218dc854e431ee665c55dc0a698a3d44a ensures that optional/required input conditions do not escape user's attention. Please see the **Screenshot-2**.| 
|When I loaded the example diffusion data and then changed the input to one of my own datasets the mask of the previous dataset remained in the Mask input field only after clicking browse and cancel is was cleared. | The previous `Browse` button is replaced with two buttons (`+` and `-`) to add/remove inputs https://github.com/qMRLab/qMRLab/commit/8de0641cc9a57606c2869137433ca0beb1fda01c. Please see the **Screenshot-3**.  In addition, when the `Path data` is set to a directory, `+` buttons prompts the browser from that directory, which was previously always pointing to the current folder regardless of what `Path data` contains. | 

Thank you so much @mfroeling for your constructive and practical comments, all of which helped me improve user friendliness of the GUI and the documentation. 

*** 

### Screenshot-1

new_button

### Screenshot-2

image

### Screenshot-3

image

### CODE REVIEW

**Comment by mfroeling** [comment]
@agahkarakuzu great work! GUIs are always a tough challenge especially with complicated models with many inputs. The changes have made a big difference in user-friendliness.

**Comment by agahkarakuzu** [comment]
Thank you @mfroeling! If you are happy with the changes, I will merge this branch following @mathieuboudreau's review.

**Comment by mfroeling** [comment]
yes im happy with the changes

**Comment by agahkarakuzu** [comment]
I reviewed this PR and resolved some issues, I will merge the branch after CI tests.

##### Manual GUI tests (general)

- [x] Does the qMRLab GUI open?
- [x] Can you change models?
- [x] Can you load a data folder for a model?
- [x] Can you view data?
- [x] Can you zoom in the image?
- [x] Can you pan out of the image?
- [x] Can you view the histogram of the data?
- [x] Can you change the color map?
- [x] Can you fit dataset (Fit data)?
- [x] Can you save/load the results?
- [x] Can you open the options panel?
- [x] Can you change option parameters?
- [x] Can you save/load option paramters?
- [x] Can you select a voxel?
- [x] Can you fit the data of that voxel ("View data fit")?
- [x] Can you simulate and fit a voxel ("Single Voxel Curve")?
- [x] Can you run a Sensitivity Analysis?
- [x] Can you simulate a Multi Voxel Distribution?

**Pull request merged**
