### PR TITLE
[WIP] Deploy tasks

### PR DESCRIPTION
**Pull request by mathieuboudreau**
Work in progress - created a pull request to try and trigger a readthedocs build.

### CODE REVIEW

**Comment by agahkarakuzu** [comment]
@mathieuboudreau this is ready to be merged, waiting for your revision. Upon merge, I will move the tag v2.3.0 and release.

**Comment by mathieuboudreau** [comment]
@agahkarakuzu would it be possible to write a quickmoxtest for qMRgenJNB.m? It's not being covered at all, and dropped the coverage by almosr 1%

**Comment by mathieuboudreau** [comment]
@agahkarakuzu I can't review the PR, since I created it. Looked at the code, and I see no major issues that stand out to me. I don't really know how to test this since it has nothing to do with qMRLab itself or the GUI, so you're best to decide to approve if you think it is ready.

**Comment by agahkarakuzu** [comment]
@mathieuboudreau I will add a quickmoxtest, then will be ready to merge.

**Comment by agahkarakuzu** [comment]
@mathieuboudreau I've pushed the test to the `quickMoxTests`, after release I can make that use data that already has been donwloaded (by qMRgenBatch) to save some time. But for now, it should solve coverage issue.

**Pull request merged**
