### PR TITLE
Echo combination

### PR DESCRIPTION
**Pull request by agahkarakuzu**

### CODE REVIEW

**Comment by agahkarakuzu** [comment]
@jeremie-fouquet 
I'll merge your fork to the upstream, but currently cannot pass the test due to some restrictions of our CI implementation. The following will walk around: 

Can you modify `.travis.yml` in your fork to look like this one:

https://github.com/qMRLab/qMRLab/blob/echo_combination/.travis.yml

If you are busy and prefer to give me write access to your fork, I can do as well.

**Comment by jeremie-fouquet** [comment]
I'll try to do it now (sorry, was a bit busy today). 

I'm not that familiar with .travis.yml files. When you say "to look like this one", would simply replace my .travis.yml by "this one" work?

**Comment by agahkarakuzu** [comment]
Sorry, I was not clear. The content of the yaml on your fork should be identical with the one in the link I shaed above. You can simply copy paste. 

Thank you so much!

**Comment by jeremie-fouquet** [comment]
All right, just did it 😃. Just let me know if something's still off.

**Comment by agahkarakuzu** [comment]
@jeremie-fouquet 🎊 Thanks! This solved the problem.

**Pull request merged**
