### PR TITLE
Correct bug in b0_dem.m (magn to Magn)

### PR DESCRIPTION
**Pull request by jeremie-fouquet**
correct a typo

### CODE REVIEW

**Comment by jeremie-fouquet** [comment]
It looks like `b0_dem.m` was not tested for data sets with 3 spatial dims. In addition to the typo mentioned in the pull request, the absence of a loop on all echoes for spatial unwrapping was corrected and dimensionality-independent lines were put out of the `if` on dimensionality.

**Comment by jeremie-fouquet** [comment]
Travis tests seem to fail because of some kind of "Unable to locate credentials" error. For instance, at the end of the [Job log of the 2112.1 test](https://travis-ci.org/qMRLab/qMRLab/jobs/530912611), we can see this:

`upload failed: Test/MoxUnitCompatible/quickMoxTests/coverage_quickMoxTests.json to s3://qmrlab/2112/coverage_quickMoxTests.json 
Unable to locate credentials`

Not sure about what I should do.

**Comment by notZaki** [comment]
The credentials error is normal when working on a fork, so no need to worry if it errors at that part. 👍

**Comment by mathieuboudreau** [comment]
^ What Zaki said. We'll change the base merge branch to a non-master branch, and then merge that one to master where the tests should then pass

**Comment by mathieuboudreau** [comment]
I merged this fork into a local branch, and reopened a PR from that branch into master in #346 so that the tests can pass (due to credential limitations from forks). Continue the discussion in that PR if needed.

**Pull request merged**
