### PR TITLE
Correct excitation flip angles in R1 and A calculations when B1 input exists

### PR DESCRIPTION
**Pull request by mathieuboudreau**
Although we were applying the "empirical" B1 correction factor to MTsat already, 

https://github.com/qMRLab/qMRLab/blob/e8c3312d2aef2c6303a3c4b52e6eaf074fdb32a5/src/Models_Functions/MTSATfun/MTSAT_exec.m#L40-L41

this is only one part of the correction needed when using B1. The flip angles in the calculations of R1, A, and MT also need to be corrected by B1 *in addition to the one above". This is also consistent with how other softwares handle B1 in MTsat, eg. hMRI:

* https://github.com/hMRI-group/hMRI-toolbox/blob/894a38be696e42a769765c313022f0bf1acafe64/hmri_calc_A.m#L41-L47
* https://github.com/hMRI-group/hMRI-toolbox/blob/894a38be696e42a769765c313022f0bf1acafe64/hmri_calc_R1.m#L41-L47

^That's for the R1 and A equations. For the MTsat equation though, they seem to to not be doing this correction prior to the empirical, which, is it a bug?

https://github.com/hMRI-group/hMRI-toolbox/blob/894a38be696e42a769765c313022f0bf1acafe64/hmri_create_MTProt.m#L684-L693

Note also their equation seems to differ from ours (in form at least, I'd need to check the factorizations/simplifications if there are any).

https://github.com/qMRLab/qMRLab/blob/e8c3312d2aef2c6303a3c4b52e6eaf074fdb32a5/src/Models_Functions/MTSATfun/MTSAT_exec.m#L34

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
Note, because the (2018) MTsat code in SCT was also based on the qMRLab MTsat code that preceded both me and @agahkarakuzu's involvement with qMRLab (the MTsat module + B1 correction [was created in 2017](https://github.com/qMRLab/qMRLab/blob/6a9587a45df82c235a5fcf519075ad70f229b6b4/Models_Functions/MTSATfun/MTSAT_exec.m)), this bug also exists there: https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/master/spinalcordtoolbox/qmri/mt.py

**Comment by mathieuboudreau** [comment]
I can understand how this error came about, particularly that long ago. First, the introduction of the B1 correction factor (relating to 0.4) wasn't really done formally back then (it was an empirical correction) and the paper wasn't super clear.

Also, it's not very intuitive. That correction factor,

https://github.com/qMRLab/qMRLab/blob/e8c3312d2aef2c6303a3c4b52e6eaf074fdb32a5/src/Models_Functions/MTSATfun/MTSAT_exec.m#L40-L41

is meant to "recalibrate" the *MTsat* value when B1 changes occurs because MTsat is intrinsically linked to the MT pulse parameters (eg MT flip angle, offset), and those aren't used in the equations. But, B1 *also* needs to be explicitely corrected for the excitation flip angles in the equations, otherwise B1 will only be corrected for the MT pulse contribution and not the excitation pulse contributions.

**Comment by mathieuboudreau** [comment]
Note: @spinicist 's QUIT software has the B1 correction (nicely factored out) for R1 and A,

https://github.com/spinicist/QUIT/blob/5af31041a2194c81306826a729e6729f4d806f3d/Source/MT/MTSatModel.cpp#L12-L20

But like hMRI, doesn't apply the B1 correction to the excitation flip angles for the MTw image in the MTsat calculation (before doing the empirical equation from Weiskopf).

https://github.com/spinicist/QUIT/blob/5af31041a2194c81306826a729e6729f4d806f3d/Source/MT/MTSatModel.cpp#L21-L22

@spinicist do you recall why you made this decision? Maybe you based yours on hMRI and its a bug, or do you have some explanation for why the `s.al_mt` aren't multiplied by `B1` in the ` auto const d` equation above?

**Comment by mathieuboudreau** [comment]
Just for reference, this is all that was said about B1 correction in Weiskopf 2013:

Screenshot 2023-11-22 at 8 19 35 AM

**Comment by spinicist** [comment]
> @spinicist do you recall why you made this decision? Maybe you based yours on hMRI and its a bug, or do you have some explanation for why the `s.al_mt` aren't multiplied by `B1` in the ` auto const d` equation above?

First, I thought it was worth directly linking #196 here.

Eventually, after shaking enough cobwebs out of my brain, I remembered that Gunther did get the correction factor published in: https://onlinelibrary.wiley.com/doi/10.1002/mrm.28899, section 2.4. This gives the justification for using the nominal flip-angles in the δ calculation rather than the corrected ones. Section 5.6 is also worth looking at.

**Comment by mathieuboudreau** [comment]
Awesome, thanks @spinicist ! On a first read, I don't fully understand it, but this is really helpful! I'll explore this more with real data, and also maybe with MTsat data simulated from our qMT-SPGR simulations module. But for sure, we need a fix in the R1 equation (otherwise the T1 maps will get heavily weighted to B1 at high B1 inhomogeneities) and A. Maybe we can merge those first, and then explore the MTsat equation one (I wonder if through our qMT simulations, we could "calculate" what the "empirical" factor ~0.4 @ 3T  is for any given protocol?)

**Comment by spinicist** [comment]
> On a first read, I don't fully understand it, but this is really helpful!

I don't fully understand it either, but I do understand that Gunther has algebra skills I can only dream of 😅 I think it comes from how the approximations in the preceding calculation steps interact.

> I wonder if through our qMT simulations, we could "calculate" what the "empirical" factor ~0.4 @ 3T is for any given protocol?

I don't think the factor C can be calculated theoretically, Gunther did a linear regression on real data acquired with different parameters. Strictly, IIRC, C is itself dependent on the bound pool fraction to an extent, so it all gets very circular. However, it clearly works well enough to give useful maps.

**Comment by mathieuboudreau** [comment]
>I don't think the factor C can be calculated theoretically, Gunther did a linear regression on real data acquired with different parameters.


I can understand that it couldn't be calculated, but I feel like simulated qMT data should be able to reproduce (to an extent) measured data, and so in absence of a wealth of measurements, I think could probably get at least a better estimate of C for another field/protocol than just using our default 0.4 which clearly isn't always applicable.

> Strictly, IIRC, C is itself dependent on the bound pool fraction to an extent, so it all gets very circular.

I can totally see that, I've run into this in qMT/MTsat a few times already haha.

>However, it clearly works well enough to give useful maps.

Yeah at the end of the day, if your MTsat map is "flat" and you use a consistent C value across measurements, the data will be useful. Across different scanners/studies less so probably, but also MTsat inherently also changes between those (as the MT pulse properties change), so this is already built into MTsat anyways.

>but I do understand that Gunther has algebra skills I can only dream of 😅

Same, hahaha

**Comment by agahkarakuzu** [comment]
@mathieuboudreau 

The following is another reference, I was also using it for model-based correction and it is as you described as well, the correction is applied to R1 and A, not to MTsat derived from un-corrected R1 and A: 

https://github.com/TardifLab/MTsatB1correction/blob/9aed6641120f998fe4dd389d8d3973af1932025c/sampleCode_calc_M0bappVsR1_1dataset.m#L93-L99

Maybe we can split b1 scaling outputs as done here to make it easier to read the code, but I leave that up to you. 

The [newer version](https://github.com/TardifLab/OptimizeIHMTimaging/tree/master/b1Correction) is here that includes the calculation of the correction factor map, but this will be dealt within another PR later.

**Review by agahkarakuzu — APPROVED** [review]

**Comment by mathieuboudreau** [comment]
> @mathieuboudreau
> 
> The following is another reference, I was using it for model-based correction and it is as you noted here, the correction is applied to R1 and A, not to MTsat derived from un-corrected R1 and A:
> 
> https://github.com/TardifLab/MTsatB1correction/blob/9aed6641120f998fe4dd389d8d3973af1932025c/sampleCode_calc_M0bappVsR1_1dataset.m#L93-L99
> 
> Maybe we can split b1 scaling outputs as done here to make it easier to read the code, but I leave that up to you.
> 

Thanks for sharing this additional source!

I opted to go the QUIT-route (factoring out the B1 from each FA) because that's the direction SCT just went, and I'd rather keep our equations consistent just for readability purpose .

**Pull request merged**
