### PR TITLE
AMICO

### PR DESCRIPTION
**Pull request by tanguyduval**
## Purpose
[NEW] Module AMICO in Diffusion

## Approach
Add AMICO toolbox: https://github.com/daducci/AMICO_matlab
Tested on MACOS and R2018a

#### Open Questions and Pre-Merge TODOs
- [x] Use github checklists. When solved, check the box and explain the answer.

- [x] Review that changed source files/lines are related to the pull request/issue
_If any files/commits were accidentally included, cherry-pick them into another branch._

- [x] Review that changed source files/lines were not accidentally deleted
_Fix appropriately if so._

- [x] Test new features or bug fix
_If not implemented/resolved adequately, solve it or inform the developer by requesting changes in your review._
_Preferably, set breakpoints in the locations that the code was changed and follow allong line by line to see if the code behaves as intended._

##### Manual GUI tests (general)

- [x] Does the qMRLab GUI open?
- [x] Can you change models?
- [x] Can you load a data folder for a model?
- [x] Can you view data?
- [x] Can you zoom in the image?
- [x] Can you pan out of the image?
- [x] Can you view the histogram of the data?
- [x] Can you change the color map?
- [x] Can you fit dataset (Fit data)?
- [x] Can you save/load the results?
- [x] Can you open the options panel?
- [x] Can you change option parameters?
- [x] Can you save/load option paramters?
- [x] Can you select a voxel?
- [x] Can you fit the data of that voxel ("View data fit")?
- [x] Can you simulate and fit a voxel ("Single Voxel Curve")?
- [x] Can you run a Sensitivity Analysis?
- [x] Can you simulate a Multi Voxel Distribution?

##### Specifications

  - Version:
  - Platform:
  - Subsystem:

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
Cool @tanguyduval ! Is this the branch that @TommyBoshkovski has been working on? He mentioned he was implementing it at a meeting this summer.

**Comment by tanguyduval** [comment]
Sorry, did not know there was an already existing branch. I implemented it
for personal use.
If the branch of @TommyBoshkovski <https://github.com/TommyBoshkovski> is
ready he can replace my work, it was really not massive in term of
implementation.

**Comment by mathieuboudreau** [comment]
Oh ok! He might not have started to work on it yet, I was just curious. But neither of you opened an issue saying that you're working on it, so I guess you are both to equally to "blame" for this confusions hahaha.

I'll wait for @TommyBoshkovski  to chime in before reviewing; either he can review it or I will. 

A+

**Comment by TommyBoshkovski** [comment]
Great job @tanguyduval, you were faster than me :). @mathieuboudreau I have been working on AMICO locally, so I'm the one to blame hahaha. However, my implementation is not ready yet, so I'll just start reviewing this one.

**Comment by tanguyduval** [comment]
@mathieuboudreau @TommyBoshkovski just to warn you that AMICO is not compatible with Octave, mainly because of mex SPAMs files that would need to be compiled for OCtave...
Travis is not passing the test because of that. Don't know what would be the strategy to pass the tests...

**Comment by mathieuboudreau** [comment]
If it's not possible to test with Travis for a good reason (like what you said), we can override the Coveralls conditions even though it fails. However, I would still setup the batch & other test(s) so that we can run it using MATLAB when reviewing PRs related to AMICO; we just wouldn't call them with Travis.

**Comment by tanguyduval** [comment]
Ok perfect, and how can I override the Coveralls conditions?

**Comment by mathieuboudreau** [comment]
Note that the Travis tests should pass regardless before merging, so AMICO should be removed from the auto-batch testing (I think that's why it's failing, as you said).

**Comment by tanguyduval** [comment]
@TommyBoshkovski can u plz approve this branch 😉

**Comment by tanguyduval** [comment]
@TommyBoshkovski thanks!

**Pull request merged**
