### PR TITLE
Monoexp t2

### PR DESCRIPTION
**Pull request by ileppe**
## Purpose
This is a new model for fitting mono-exponential T2 data. It was mostly implemented by @agahkarakuzu and it includes both linear and exponential fits.

## Approach
The default options for fitting seem to result in T2 maps close the the Siemens output. A partial dataset is included for travis tests

##### Manual GUI tests (general)

- [x] Does the qMRLab GUI open?
- [x] Can you change models?
- [x] Can you load a data folder for a model?
- [x] Can you view data?
- [x] Can you zoom in the image?
- [x] Can you pan out of the image?
- [x] Can you view the histogram of the data?
- [x] Can you change the color map?
- [x] Can you fit dataset (Fit data)?
- [x] Can you save/load the results?
- [x] Can you open the options panel?
- [x] Can you change option parameters?
- [x] Can you save/load option paramters?
- [x] Can you select a voxel?
- [x] Can you fit the data of that voxel ("View data fit")?
- [x] Can you simulate and fit a voxel ("Single Voxel Curve")?
- [x] Can you run a Sensitivity Analysis?
- [x] Can you simulate a Multi Voxel Distribution?

##### Specifications

  - Version:
  - Platform: linux
  - Subsystem:

### CODE REVIEW

**Comment by agahkarakuzu** [comment]
Thank you for the PR @ileppe! 

Looks like the model is missing from the `static_savedModelsforRetrocompatibility` folder. 

```diff
- failure: load: unable to find file mono_t2.qmrlab.mat
-  qMRloadObj:10 (/tmp/oct-Aql8hi/Common/qMRloadObj.m)
```

Another step is to update ` [MethodList, pathmodels] = qMRLab_static_Models` file. This won't affect the test, but required for standalone build. 

I will add these to the Wiki page.

**Comment by agahkarakuzu** [comment]
Thank you @ileppe <3

**Comment by agahkarakuzu** [comment]
Octave `random` does not have `rician`. Here is the list for the ones available: 

https://octave.sourceforge.io/statistics/function/random.html

**Comment by agahkarakuzu** [comment]
I solved the other problem on `mp2rage` branch, you can just change `rician` to something Octave has, then this PR should be ready to go.

**Comment by ileppe** [comment]
@agah thank you for checking everything and fixing my issues!

**Pull request merged**
