### PR TITLE
Update doc

### PR DESCRIPTION
**Pull request by agahkarakuzu**

### CODE REVIEW

**Comment by tanguyduval** [comment]
@agahkarakuzu I could compile the doc without any issue.
I just saw some problems with qsm_sb:
  * Header is not complete
````matlab
     Explanation of all parameters:
        chiSBM
        chiSB
        chiL2M
        chiL2
        nfm
        unwrappedPhase
        maskOut (maskSharp, gradientMask or same as the input)
````

  * Output map does not make sense to me:
image

**Comment by agahkarakuzu** [comment]
@tanguyduval I did not know that it was on purpose. Thanks for the input. 

There is a long explanation of why the figure is like that, but I will fix it on this branch.

**Comment by agahkarakuzu** [comment]
@mathieuboudreau this branch is ready to be merged: 

* Resolves issues regarding `qsm_sb` documentation. 
     * Now the output image makes sense
     * Header is complete 

This required a workaround, because unlike other voxelwise=0 methods, this one is computationally intensive. You can see explanations in the doc. 
https://qmrlab.readthedocs.io/en/update_doc/qsm_sb_batch.html#9

* Fixes PR template issue.

**Comment by agahkarakuzu** [comment]
Used my administrator privileges to merge this pull request. Changes in documentation and minor edits on community files.

**Pull request merged**
