### PR TITLE
Update deployment/azure badge on readme

### PR DESCRIPTION
**Pull request by notZaki**
## Purpose
The `deployment` badge on the readme points to a site that gives a 401 error (unauthorized access).

## Approach

Replaced old badge with the status badge from the azure pipelines/builds page. This will/should redirect to the most recent azure build for the master branch.
 
The readme text was also changed to have each badge on a new line. 
This makes the raw text easier to read (multiple shorter lines instead of one very long line) without affecting the rendered readme (badges still appear on the same line)

**Other alternatives**  
The badge's URL could instead be changed from `https://devops.azure.com/qmrlab` (401 error) to `https://devops.azure.com/qmrlab/qmrlab` (main azure page) or to `https://dev.azure.com/qmrlab/qmrlab/_build?` (shows all builds). 

#### Open Questions and Pre-Merge TODOs

It doesn't look like the azure build is doing much right now so maybe the badge is better off being removed until the azure CI is fully configured? 🤷‍♂

### CODE REVIEW

**Comment by agahkarakuzu** [comment]
@notZaki can you visit this link:

https://dev.azure.com/qmrlab/qMRLab/_releaseProgress?_a=release-pipeline-progress&releaseId=41

**Comment by notZaki** [comment]
> https://dev.azure.com/qmrlab/qMRLab/_releaseProgress?_a=release-pipeline-progress&releaseId=41

I can access that link. 👍 

If the badge is supposed to be for the release, then there might be a way to generate it from azure pipeline/releases-2/options.

**Comment by agahkarakuzu** [comment]
There is a way to generate a badge displaying the status of the any given (latest) release stage, instead of generating a badge per release + per stage. 

Screenshot from 2019-05-21 14-50-30

Right now they are displaying the status after Release-2.Note that I only display the one from the octjn stage. I don't know why they don't provide a joint (if all) badge. 

V95
https://vsrm.dev.azure.com/qmrlab/_apis/public/Release/badge/46799180-12b7-4319-b8e7-94e1d39047e7/2/7

octjn
https://vsrm.dev.azure.com/qmrlab/_apis/public/Release/badge/46799180-12b7-4319-b8e7-94e1d39047e7/2/7

mcrgui
https://vsrm.dev.azure.com/qmrlab/_apis/public/Release/badge/46799180-12b7-4319-b8e7-94e1d39047e7/2/8

I think pointing hyprelink to the list of all releases (https://dev.azure.com/qmrlab/qmrlab/_release?) is the outstanding option.

**Comment by agahkarakuzu** [comment]
I am closing this PR, will revise badges upon next release.

**Pull request closed without merging**
