### PR TITLE
Export MTR map in MTsat

### PR DESCRIPTION
**Pull request by jvelazquez-reyes**
I handled the options panel checkbox as in the dti module.

### CODE REVIEW

**Comment by agahkarakuzu** [comment]
Cool! Thanks for the quick response. 

- You can change the checkbox name from 'Export' to 'Enabled', 
so that in the code it is ExportMTR_Enabled being true or false. 

- You may need to update example datasets if you made Enabled true by default, no need otherwise.

**Comment by jvelazquez-reyes** [comment]
`ExportMTR_Enabled` is set to `true` as default. I also updated the demo dataset in OSF.

**Comment by agahkarakuzu** [comment]
Cool, one other change would be using GUI behaviour as set in qsm_sb. I mean instead of handling ### manually.

**Comment by jvelazquez-reyes** [comment]
I think it's done

**Comment by agahkarakuzu** [comment]
Yup! I wanted you to do this for consistency, that's why I pointed `qsm_sb` in the origin [issue](https://github.com/qMRLab/qMRLab/issues/469#issuecomment-1136833744). 

If you check the developer documentation below:

https://github.com/qMRLab/qMRLab/wiki/Guideline:-GUI#dynamic-panels

you can see guidelines about  managing dynamic GUI behaviour. 

In the future, when you are adding something, that'd be cool if you can check the developer docs first. This way you don't have to reverse engineer [something](https://github.com/qMRLab/qMRLab/pull/470#issue-1248286196) that already has been (I had to do such stuff for GUI quite a bit). 

 If what you'd like to implement a feature does not exist in the dev docs, then you can first implement, then add it to the docs :)

**Pull request merged**
